#!/bin/bash
#ROOT=$(cat /etc/group | grep sudo)
iam=$(whoami)

#if [ $ROOT = $iam ]
if groups "$iam" | grep &>/dev/null '\broot\b'
then
  echo "You are a root user."
else
  echo "You are not a root user"
fi
